version: '3.7'

services:
  db:
    image: postgres:11.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  minio:
    image: minio/minio:RELEASE.2020-08-13T02-39-50Z
    ports: 
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniostorage
    command: server /data
    restart: always
    volumes:
      - minio:/data

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "test"
      RABBITMQ_DEFAULT_PASS: "omnitest"

volumes:
    minio:
    database:
    rabbitmq: